### ISSUE TITLE
Add Business Rule Action has disappeared

### ISSUE THREAD

**Issue by nozurbina** [oxygenxml/dim#5]
There used to be a button to add a new business rule when I was working in the styleguide map. I upgraded (as instructed) to Oxygen 16.1 and the button disappeared. I can't see how to get it back.

**Comment by georgebina** [comment]
Hi Noz,

Please make sure you update the framework to the latest from GitHub and you have the dim.xpr as the open project. The "Add business rule" and "Add link to style guide" actions are added as part of a framework which is an extension of the DITA framework and it is added by setting the [dim]/frameworks as additional frameworks folder at the project level in Options->Preferences -- Document Type Association / Locations. If the dim.xpr project is not the current project then oXygen will not load the DIM framework.

Let me know if you still have problems.
Regards,
George

**Comment by nozurbina** [comment]
Hi George, I only installed it yesterday so I don't think I can have an old framework. Is it possible that it's because I have made another extension to my DITA framwork in order to make it validate all DITA against Schematron? Can you not have two extended frameworks running at once maybe?

**Comment by georgebina** [comment]
Yes, that enters in conflict with this DIM extension - a document matches only one framework. If you change the DITA framework itself then the DIM extension should be applied on that modified DITA framework, but if you made another extension that that will compete with the DIM extension and depending on the frameworks priority one of them will win.
Shall I assume the issue is solved now that you closed this?

**Comment by georgebina** [comment]
To see exactly what framework matched a document, open the Properties view from Window->Show View->Properties and look at the "Document Type" entry - that should be DITA DIM if the DIM framework is used.

**Comment by georgebina** [comment]
I think the best way to work will be to follow the idea of the DIM project and configure a DITA extension in your own project by placing the Document Type Association / Location page at project level and setting the `${pd}/frameworks` as an additional frameworks folder (${pd]=project directory), then save your DITA extension framework as an external framework, in a subfolder withing `${pd}/frameworks`. Thus you will get those specific settings only when you have that project open and those changes will not interfere with any other projects.

On another note, if you look in Options->Preferences -- Document Type Associations then you will see all the available frameworks, listed in their priority order and you can easily disable any of them using the check box immediately to the left of a framework name.

**Comment by nozurbina** [comment]
Hi George,

I was able to get the buttons back by turning off the extended DITA
framework but I can't understand your suggestion enough to see if it gets
me what I want (all DITA validated, yet still having the buttons when I am
in the styleguide project). I am not familiar enough with oXygen Frameworks
I think.

On 20 March 2015 at 07:16, George Bina <notifications@github.com> wrote:

> I think the best way to work will be to follow the idea of the DIM project
> and configure a DITA extension in your own project by placing the Document
> Type Association / Location page at project level and setting the
> ${pd}/frameworks as an additional frameworks folder (${pd]=project
> directory), then save your DITA extension framework as an external
> framework, in a subfolder withing ${pd}/frameworks. Thus you will get
> those specific settings only when you have that project open and those
> changes will not interfere with any other projects.
>
> On another note, if you look in Options->Preferences -- Document Type
> Associations then you will see all the available frameworks, listed in
> their priority order and you can easily disable any of them using the check
> box immediately to the left of a framework name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oxygenxml/dim/issues/5#issuecomment-83924429>.
>



-- 
Noz

Content Strategist, urbinaconsulting.com <http://bit.ly/uc_site>
Co-Author of "Content Strategy: Connecting the dots between business, brand
and benefits <http://www.thecontentstrategybook.com>". In stores now:
thecontentstrategybook.com <http://www.thecontentstrategybook.com>

**Comment by georgebina** [comment]
Hi Noz,

See revision bed1099c67e72caf4e9886e2fa27b9e6303668e5.
I defined a project within test/project/dimTest.xpr. This sets the Options -> Preferences -- Document Type Association to be stored at project level by selecting "Project Options" at the bottom of that options page and then I extended the DITA framework and created the "DITA - DIM Test" framework. This has the storage set to "Internal" which means it will be stored within the options storage, which is the .xpr file itself because I set that options page to be stored within the project. Then I edited the framework extension, locating the DITA validation scenario in the Validation tab and adding a new validation unit that validates the topic as an XML document with the Schematron schema "${pdu}/../../info-model/rules/rules.sch" - where ${pdu} will be expanded to the project directory URL, that means it will be the test/project folder, so the schema location points back to the DIM project's rule.sch generated file.

Now, if you want to test how the DIM rules.sch work, just double click on the test/project/dimTest.xpr and here any topic you open will be validated also with rules.sch. When you work on DIM itself, double click on the dim/dim.xpr that is added in the dimTest.xpr project so you get the DITA DIM extension that provides the Add rule, etc. actions.

Hope this helps,
George

**Comment by nozurbina** [comment]
It´s working now. I had to use your project though. When I tried to
reproduce the steps it didn´t work for me :

On 21 March 2015 at 07:32, George Bina <notifications@github.com> wrote:

> Closed #5 <https://github.com/oxygenxml/dim/issues/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oxygenxml/dim/issues/5#event-261028763>.
>



-- 
Noz

Content Strategist, urbinaconsulting.com <http://bit.ly/uc_site>
Co-Author of "Content Strategy: Connecting the dots between business, brand
and benefits <http://www.thecontentstrategybook.com>". In stores now:
thecontentstrategybook.com <http://www.thecontentstrategybook.com>
